#!/bin/bash
#
#
# License:      GNU General Public License (GPL)
#
# Sync
#    Description: Manage a Sync process
#         Author: Carsten Wolff <carsten.wolff@credativ.de>
#         Author: Patrick Schoenfeld <patrick.schoenfeld@credativ.de>
#
#
# usage: ./Sync {start|stop|status|monitor|validate-all|meta-data}
#

OCF_ROOT=/usr/lib/ocf
: ${OCF_FUNCTIONS_DIR=${OCF_ROOT}/lib/heartbeat}
. ${OCF_FUNCTIONS_DIR}/ocf-shellfuncs

# Defaults
OCF_RESKEY_binary_default="/usr/local/bin/Sync"

: ${OCF_RESKEY_binary=${OCF_RESKEY_binary_default}}

usage() {
    cat <<-EOT
    usage: $0 {start|stop|status|monitor|validate-all|meta-data}
EOT
}

meta_data() {
    cat <<-EOF
<?xml version="1.0"?>
<!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
<resource-agent name="Sync">
<version>1.0</version>

<longdesc lang="en">
Resource script for Sync.
Manages a Sync.
</longdesc>
<shortdesc lang="en">Manages a lsysncd instance</shortdesc>

<parameters>
<parameter name="binary" unique="0" required="0">
<longdesc lang="en">
Location of the Sync binary
</longdesc>
<shortdesc lang="en">Syncr binary</shortdesc>
<content type="string" default="${OCF_RESKEY_binary_default}" />
</parameter>
</parameters>

<actions>
<action name="start" timeout="30" />
<action name="stop" timeout="30" />
<action name="status" timeout="10" />
<action name="monitor" depth="0" timeout="30" interval="20" />
<action name="monitor" role="Master" depth="0" timeout="30" interval="10" />
<action name="monitor" role="Slave" depth="0" timeout="30" interval="30" />
<action name="promote" timeout="120" />
<action name="demote" timeout="120" />
<action name="notify" timeout="90" />
<action name="validate-all" timeout="5" />
<action name="meta-data" timeout="5" />
</actions>
</resource-agent>
EOF
}

Sync_status() {
	${OCF_RESKEY_binary} status

	return $?
}

Sync_start() {
	Sync_status

	if [[ $? -eq 1 ]]; then
		ocf_log info "START: starting Sync instance"
		${OCF_RESKEY_binary} start
	fi

	while :
	do
		Sync_status
		rc=$?
		if [[ $rc -eq 0 ]]; then
			break;
		fi
		sleep 1
		ocf_log debug "Sync still not started. Waiting ..."
	done
	ocf_log info "Sync is started."

	return $rc
}

Sync_stop() {
	Sync_status

	if [[ $? -eq $OCF_SUCCESS ]]; then
		ocf_log info "stopping Sync"
		${OCF_RESKEY_binary} stop
	fi
	return $?
}

Sync_monitor() {
	if ocf_is_probe; then
		ocf_log debug "$RESOURCE monitor PROBE"
	else
		ocf_log debug "$RESOURCE monitor"
	fi

	Sync_status
	if [[ $? -ne 0 ]]; then
		ocf_log warn "$RESOURCE monitor: Sync not running"
		return $OCF_NOT_RUNNING
	fi

	ocf_log info "$RESOURCE monitor: Sync is running"
	return $OCF_SUCCESS
}

case "$1" in
  meta-data)    meta_data
                exit $OCF_SUCCESS;;
  usage|help)   usage
                exit $OCF_SUCCESS;;
esac

case "$1" in
  start)        Sync_start;;
  stop)         Sync_stop;;
  status)       Sync_status;;
  monitor)      Sync_monitor;;
  validate-all) exit $OCF_SUCCESS;;
 *)             usage
                exit $OCF_ERR_UNIMPLEMENTED;;
esac
